project/apps/films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path(
        '',
        views.ListFilmsView.as_view(),
        name='list'
    ),
    path(
        'cadastrar',
        views.CreateFilmView.as_view(),
        name='create'
    ),
    path(
        'editar/<int:pk>',
        views.EditFilmView.as_view(),
        name='edit'
    ),
    path(
        'relatorio',
        views.ReportFilms.as_view(),
        name='report'
    ),
    path(
        'prepare-export-excel',
        views.PrepareExportFilms.as_view(),
        name='prepare_export_excel'
    ),
    path(
        'export-excel',
        views.ExportFilms.as_view(),
        name='export_excel'
    ),
    path(
        'import-excel',
        views.ImportExcel.as_view(),
        name='import_excel'
    )
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('filmes/', include('apps.films.urls')),
    path('autenticacao/', include('apps.authentication.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/films/models.py
from django.db import models
from django.contrib.auth.models import User


class Film(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    assisted_in = models.DateField(blank=True, null=True)
    would_like = models.BooleanField()


class FilmExportRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report = models.FileField(upload_to='films/exports/%Y/%m/%d/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    started_at = models.DateTimeField(blank=True, null=True)
    finished_at = models.DateTimeField(null=True, blank=True)


class FilmImportRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report = models.FileField(upload_to='films/imports/%Y/%m/%d/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    started_at = models.DateTimeField(blank=True, null=True)
    finished_at = models.DateTimeField(null=True, blank=True)

project/apps/films/forms/film_form.py
from django import forms
from ..models import Film


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['name', 'description', 'assisted_in', 'would_like']
        labels = {
            'name': 'Nome',
            'description': 'Descrição',
            'assisted_in': 'Assistido em',
            'would_like': 'Gostaria de assistir'
        }
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),
            'assisted_in': forms.TextInput(
                attrs={
                    'class': 'form-control mask-date'
                }
            ),
            'would_like': forms.CheckboxInput(
                attrs={
                    'class': 'form-check-input'
                }
            )
        }

project/apps/films/views.py
from .models import Film, FilmExportRequest, FilmImportRequest
from .tasks import export_films_excel, import_excel_to_films
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, \
    UpdateView, View
from django.http import JsonResponse
from .forms import FilmForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.utils import timezone


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class ListFilmsView(ListView):
    template_name = 'films/pages/list.html'
    model = Film
    context_object_name = 'films'

    def get_queryset(self):
        qs = super().get_queryset()
        search = self.request.GET.get('search', None)
        qs = qs.filter(user=self.request.user).order_by('-id')
        if search:
            qs = qs.filter(
                name__icontains=search
            )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(**kwargs)
        additional_url_query = ''
        paginator = Paginator(ctx['films'], 10)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        pagination_range = paginator.get_elided_page_range(page_number)
        ctx.update(
            {
                'films': page_obj,
                'paginator': paginator,
                'pagination_range': pagination_range,
                'additional_url_query': additional_url_query

            }
        )
        return ctx


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class CreateFilmView(CreateView):
    model = Film
    form_class = FilmForm
    template_name = 'films/pages/create.html'
    success_url = reverse_lazy('films:list')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super().form_valid(form)


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class EditFilmView(UpdateView):
    model = Film
    form_class = FilmForm
    template_name = 'films/pages/edit.html'
    success_url = reverse_lazy('films:list')


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class ReportFilms(View):
    def get(self, request):
        would_like_films = Film.objects.filter(would_like=True, user=request.user).count()
        assisted_films = Film.objects.filter(would_like=False, user=request.user).count()
        return JsonResponse(
            data={
                'data': [would_like_films, assisted_films]
            }
        )


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class PrepareExportFilms(View):
    def get(self, request):
        export_request = FilmExportRequest.objects.create(
            user=request.user)
        result = export_films_excel.apply_async([export_request.id])
        messages.warning(
            request,
            'O processamento do seu formulário está em andamento. Um botão de exportação será exibido assim que estiver concluído.'
        )
        request.session['task_id'] = result.id
        request.session['export_request_id'] = export_request.id
        return redirect(
            'core:home'
        )


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class ExportFilms(View):
    def get(self, request):
        task_pk = request.session.get('task_id', None)
        export_request_id = request.session.get('export_request_id', None)

        result = export_films_excel.AsyncResult(task_pk)

        if result.successful():
            del (request.session['task_id'])
            del (request.session['export_request_id'])
            export_request = FilmExportRequest.objects.get(
                pk=export_request_id)
            with open(export_request.report.path, 'rb') as file:
                response = HttpResponse(
                    file.read(),
                    content_type='application/ms-excel'
                )
                response['Content-Disposition'] = 'attachment; filename="relatorio.xls"'
                return response
        else:
            messages.warning(request, 'Seu formulário ainda está sendo processado...')
            return redirect(
                'core:home'
            )


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class ImportExcel(View):
    def post(self, request):
        excel_file = request.FILES['excel_file']
        import_request = FilmImportRequest.objects.create(
            user=request.user,
            report=excel_file,
            created_at=timezone.now()
        )
        import_excel_to_films.apply_async([import_request.id])
        messages.success(request, 'Seus filmes estão sendo criados!')
        return redirect(
            'films:create'
        )

project/apps/films/templates/films/pages/create.html
{% extends "global/base.html" %}
{% load static %}

{% block title %}Cadastrar Filme{% endblock title %}

{% block content %}
    <form class="mt-2" method="POST" action="{% url 'films:import_excel' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input required type="file" name="excel_file" class="form-control">
        <div class="form-text">  
            Insira os seguintes nomes nas colunas do Excel: "Nome", "Descrição", "Assistido em", "Gostaria de assistir". 
            Por exemplo, se já assistiu, coloque "assistido" na coluna "Gostaria de assistir" e a data em "Assistido em"; 
            caso contrário, insira apenas "sim" na coluna "Gostaria de assistir".
        </div>
        <button type="submit" class="btn btn-secondary">Importar por Excel</button>
    </form>

    {% include "global/partials/form.html" with btn_text="Cadastrar" %}
{% endblock content %}

{% block scripts %}
    <script src="{% static "films/plugin/jquery.mask.js" %}"></script>
    <script src="{% static "films/js/form_mask.js" %}"></script>
    <script src="{% static "films/js/disable_date.js" %}"></script>
{% endblock scripts %}

project/apps/films/templates/films/pages/edit.html
{% extends "global/base.html" %}
{% load static %}

{% block title %}Editar Filme{% endblock title %}

{% block content %}
    {% include "global/partials/form.html" with btn_text="Editar" %}
{% endblock content %}

{% block scripts %}
    <script src="{% static "films/plugin/jquery.mask.js" %}"></script>
    <script src="{% static "films/js/form_mask.js" %}"></script>
    <script src="{% static "films/js/disable_date.js" %}"></script>
{% endblock scripts %}

project/apps/films/templates/films/pages/list.html
{% extends "global/base.html" %}

{% block title %}Listar Filmes{% endblock title %}

{% block content %}
    <h1 class="text-center">Seus Filmes</h1>
    <div class="row justify-content-center">
        {% for film in films %}
            <div class="col">
                <div class="card mb-3" style="width: 18rem;">
                    <div class="card-body">
                    <h5 class="card-title">{{ film.name }}</h5>
                    <p class="card-text">{{ film.description }}</p>
                    {% if film.would_like %}
                        <button class="btn btn-primary">Gostaria de Assistir!</button>
                    {% else %}
                        <button type="button" class="btn btn-success">Assistido!</button>
                    {% endif %}
                        <a class="btn btn-secondary" href="{% url 'films:edit' film.pk %}">Editar</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
            {% include "global/partials/pagination.html" with page_obj=films %}
        </div>
    </div>
{% endblock content %}