project/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    )
]

project/apps/films/urls.py
from django.urls import path
from . import views

app_name = 'films'

urlpatterns = [
    path(
        '',
        views.ListFilmsView.as_view(),
        name='list'
    ),
    path(
        'cadastrar',
        views.CreateFilmView.as_view(),
        name='create'
    ),
    path(
        'editar/<int:pk>',
        views.EditFilmView.as_view(),
        name='edit'
    ),
    path(
        'relatorio',
        views.ReportFilms.as_view(),
        name='report'
    ),
    path(
        'prepare-export-excel',
        views.PrepareExportFilms.as_view(),
        name='prepare_export_excel'
    ),
    path(
        'export-excel',
        views.ExportFilms.as_view(),
        name='export_excel'
    ),
    path(
        'import-excel',
        views.ImportExcel.as_view(),
        name='import_excel'
    )
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('filmes/', include('apps.films.urls')),
    path('autenticacao/', include('apps.authentication.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/core/models.py
from django.db import models

# Create your models here.

project/apps/core/views.py
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(
    login_required(login_url='authentication:login', redirect_field_name='next'),
    name='dispatch'
)
class HomeView(TemplateView):
    template_name = 'core/pages/home.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(**kwargs)
        task_id = self.request.session.get('task_id', None)
        export_request_id = self.request.session.get('export_request_id')
        if self.request.session.get('task_id', None):
            ctx.update(
                {
                    'task_id': task_id,
                    'export_request_id': export_request_id
                }
            )
        return ctx

project/apps/core/templates/core/pages/home.html
{% extends "global/base.html" %}
{% load static %}

{% block title %}Página Principal{% endblock title %}

{% block content %}
<h1 class="text-center">Relatório</h1>
<div class="d-flex justify-content-center">
    <a href="{% url 'films:prepare_export_excel' %}" class="btn btn-primary">Preparar Excel</a>
    {% if task_id %}
        <form action="{% url 'films:export_excel' %}" method="GET">
            <input type="hidden" value="{{ task_id }}">
            <input type="hidden" value="{{ export_request_id }}">
            <button type="submit" class="btn btn-success">Exportar Excel</button>
        </form>
    {% endif %}
</div>
<div class="row">
    <div class="col d-flex justify-content-center">
        <canvas id="chartFilms" width="500" height="500"></canvas>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
<script src="{% static 'core/js/chart.js' %}"></script>
<script>
    window.onload = function(e){
        renderize_chart_films("{% url 'films:report' %}")
    }
</script>
{% endblock scripts %}